spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/issue_tracker
    username: root
    password: 1234

logging:
  level:
    org:
      hibernate:
        type: debug

